FROM ubuntu
WORKDIR /app
COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y python3 python3-pip fio curl wget
RUN pip3 install -r requirements.txt
COPY . .
CMD [ "python3", "main.py"]